kind: Service
apiVersion: v1
metadata:
  name: {{ .ClusterManagerName }}-placement
  namespace: {{ .ClusterManagerNamespace }}
  labels:
    app: {{ .ClusterManagerName }}-placement-controller
spec:
  selector:
    app: clustermanager-placement-controller
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
