kind: Service
apiVersion: v1
metadata:
  name: {{ .ClusterManagerName }}-placement
  namespace: {{ .ClusterManagerNamespace }}
  labels:
    app: {{ .ClusterManagerName }}-placement-controller
spec:
  selector:
    app: clustermanager-placement-controller
  ports:
  - name: debugger
    port: 9443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
